DATA:
    version: 'mini'
    dataroot: '/home/ruslan/datasets/nuscenes'
    osm_path: '/home/ruslan/datasets/osm'  # Open Street Maps path

    H: 900
    W: 1600
    resize_lim: [0.386, 0.450]
    final_dim: [256, 704]
    bot_pct_lim: [0.0, 0.22]
    rot_lim: [-5.4, 5.4]
    rand_flip: False
    ncams: 1
    cams: ['CAM_FRONT']
#    cams: ['CAM_FRONT_LEFT', 'CAM_FRONT', 'CAM_FRONT_RIGHT',
#           'CAM_BACK_LEFT',  'CAM_BACK',  'CAM_BACK_RIGHT']

    xbound: [0.0, 32.0, 0.125]  # TODO: check it! x and y should be changed for different Dataloaders
    ybound: [-16.0, 16.0, 0.125]
    zbound: [-10.0, 10.0, 20.0]
    dbound: [4.0, 45.0, 1.0]

#    xbound: [ 0.0, 69.12, 0.16 ]
#    ybound: [ -39.68, 39.68, 0.16 ]
#    zbound: [ -10.0, 10.0, 20.0 ]
#    dbound: [ 4.0, 45.0, 1.0 ]

TRAIN:
    lr: 0.001  # model learning rate
    weight_decay: 0.0000001  # weights decay hyperparameter
    pos_weight: 2.13
    max_grad_norm: 5
    batch_size: 2  # Mini-Batch size
    num_workers: 12  # Number of cpu workers for dataloaders
    num_epochs: 20  # 10000
    gpuid: 0  # GPU id
    model_name: "lss_nuscenes"  # Model Name with specifications
    discr_start_train_epoch: 0  # epoch to start training discriminator
    lr_D: 0.001  # discriminator learning rate
    static_weight_D: 0.2  # static layout weight for discriminator loss
    dynamic_weight_D: 0.8  # dynamic layout weight for discriminator loss
    lambda_D: 0.01  # tradeoff weight for discriminator loss
